apiVersion: v1
kind: Service
metadata:
  name: lb-process-video
  namespace: techChallenge
spec: 
  selector:
    app: process-video
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer