apiVersion: v1
kind: Service
metadata:
  name: sv-in-out
  namespace: techChallenge
spec: 
  selector:
    app: in-out
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

