name: Deploy 
on:
  workflow_dispatch:

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "tech-challenge"
jobs:
  deploy:
    name: Deploy AWS Academy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}

      - name: Kube Apply ConfigMap in-out
        run: kubectl apply -f k8s/configmap-in-out.yaml
      - name: Kube Apply ConfigMap process video
        run: kubectl apply -f k8s/configmap-process-video.yaml
      - name: Kube Apply Service in-out
        run: kubectl apply -f k8s/service-in-out.yaml
      - name: Kube Apply Service Process Video
        run: kubectl apply -f k8s/service-process-video.yaml 
      - name: Kube Apply HPA in-out
        run: kubectl apply -f k8s/hpa-in-out.yaml
      - name: Kube Apply HPA process-video
        run: kubectl apply -f k8s/hpa-process-video.yaml

  
      
